version: '3.9'

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: DADIL
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: senha@123
    ports:
      - '5434:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./init_db:/docker-entrypoint-initdb.d
